server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_wallet_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true